"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Bot, Plus, Send, Sparkles, Trash2 } from "lucide-react";
import { api, type Agent, type Skill } from "@/lib/api";

type Draft = { name: string; description: string; instructions: string; skill_slugs: string[] };
type ChatMessage = { role: "user" | "assistant"; content: string };
const emptyDraft: Draft = { name: "", description: "", instructions: "", skill_slugs: [] };

function Header({ title }: { title: string }) { return <header className="agent-page-header"><Link href="/app"><ArrowLeft size={17} />工作区</Link><span><Bot size={18} />{title}</span></header>; }

export function AgentCatalog() {
  const [items,setItems]=useState<Agent[]>([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;api<{agents:Agent[]}>("/api/v1/agents").then(r=>{if(active)setItems(r.agents)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Agent 加载失败")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};},[]);
  return <main className="agent-page"><Header title="Agent 管理"/><div className="agent-page-body"><div className="agent-page-title"><div><p className="eyebrow">Agents</p><h1>为不同工作，准备合适的 Agent</h1><p>创建专属提示词和 Skill 组合，再从详情页或新会话开始使用。</p></div><Link className="primary-button" href="/app/agents/new"><Plus size={16}/>创建 Agent</Link></div>{error&&<p role="alert" className="settings-error">{error}</p>}{loading?<p>正在加载…</p>:<div className="agent-card-grid">{items.map(a=><Link href={`/app/agents/${encodeURIComponent(a.slug)}`} className="agent-card" key={a.slug}><span className="agent-card-icon"><Bot size={22}/></span><div><small>{a.builtin?"内置 Agent":"我的 Agent"}</small><h2>{a.name}</h2><p>{a.description||"尚未填写简介"}</p></div><span className="agent-card-foot">{a.skill_slugs.length?`${a.skill_slugs.length} 个 Skill`:"通用能力"}<ArrowRight size={16}/></span></Link>)}</div>}</div></main>;
}

export function AgentLanding({ slug }: { slug:string }) {
  const [item,setItem]=useState<Agent|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState(false);const router=useRouter();
  useEffect(()=>{let active=true;api<Agent>(`/api/v1/agents/${encodeURIComponent(slug)}`).then(a=>{if(active)setItem(a)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Agent 不存在")});return()=>{active=false};},[slug]);
  async function remove(){if(!item||item.builtin||busy)return;setBusy(true);setError("");try{await api(`/api/v1/agents/${item.id}`,{method:"DELETE",body:JSON.stringify({version:item.version})});router.push("/app/agents");}catch(e){setError(e instanceof Error?e.message:"删除失败");setBusy(false)}}
  return <main className="agent-page"><Header title="Agent 详情"/><div className="agent-page-body">{error&&<p role="alert" className="settings-error">{error}</p>}{item?<div className="agent-landing"><span className="agent-landing-icon"><Bot size={34}/></span><small>{item.builtin?"内置 Agent":"我的 Agent"}</small><h1>{item.name}</h1><p className="agent-landing-description">{item.description}</p><div className="agent-landing-actions"><Link className="primary-button" href={`/app?agent=${encodeURIComponent(item.slug)}`}>和 {item.name} 开始会话 <ArrowRight size={16}/></Link>{!item.builtin&&<Link className="secondary-button" href={`/app/agents/${encodeURIComponent(slug)}/edit`}>编辑 Agent</Link>}</div><section><h2>这个 Agent 如何工作</h2><p>{item.builtin?item.description:item.instructions}</p></section><section><h2>预设 Skill</h2><p>{item.skill_slugs.length?item.skill_slugs.join(" · "):"没有预设 Skill；会话中仍可自行安装。"}</p></section>{!item.builtin&&<div className="agent-danger">{confirm?<><span>删除后无法恢复 Agent，但已有会话保留原有设置。</span><button type="button" disabled={busy} onClick={()=>setConfirm(false)}>取消</button><button type="button" disabled={busy} onClick={()=>void remove()}>确认删除</button></>:<button type="button" onClick={()=>setConfirm(true)}><Trash2 size={15}/>删除 Agent</button>}</div>}</div>:!error?<p>正在加载…</p>:null}</div></main>;
}

export function AgentEditor({ slug }: { slug?:string }) {
  const router=useRouter();const [existing,setExisting]=useState<Agent|null>(null);const [draft,setDraft]=useState<Draft>(emptyDraft);const [skills,setSkills]=useState<Skill[]>([]);const [messages,setMessages]=useState<ChatMessage[]>([{role:"assistant",content:"说说你希望这个 Agent 帮你完成什么。我会和你一起整理名称、职责、提示词和合适的 Skill。"}]);const [input,setInput]=useState("");const [suggestion,setSuggestion]=useState<Draft|null>(null);const [error,setError]=useState("");const [chatError,setChatError]=useState("");const [busy,setBusy]=useState(false);const [chatBusy,setChatBusy]=useState(false);const pending=useRef(false);const chatPending=useRef(false);
  useEffect(()=>{let active=true;Promise.all([api<{skills:Skill[]}>("/api/v1/skills"),slug?api<Agent>(`/api/v1/agents/${encodeURIComponent(slug)}`):Promise.resolve(null)]).then(([list,agent])=>{if(!active)return;setSkills(list.skills);if(agent){if(agent.builtin){setError("内置 Agent 不支持编辑");return}setExisting(agent);setDraft({name:agent.name,description:agent.description,instructions:agent.instructions,skill_slugs:agent.skill_slugs});}}).catch(e=>{if(active)setError(e instanceof Error?e.message:"加载失败")});return()=>{active=false};},[slug]);
  async function send(event:FormEvent){event.preventDefault();const text=input.trim();if(!text||chatPending.current)return;chatPending.current=true;setChatBusy(true);setChatError("");const next=[...messages,{role:"user" as const,content:text}];setMessages(next);setInput("");try{const response=await api<{reply:string;draft:Draft|null}>("/api/v1/agent-builder/chat",{method:"POST",body:JSON.stringify({messages:next.slice(1).slice(-20)})});setMessages([...next,{role:"assistant",content:response.reply}]);if(response.draft)setSuggestion(response.draft);}catch(e){setChatError(e instanceof Error?e.message:"创建助手无法回复，请重试");setMessages(messages);setInput(text)}finally{chatPending.current=false;setChatBusy(false)}}
  async function save(event:FormEvent){event.preventDefault();if(pending.current)return;pending.current=true;setBusy(true);setError("");try{const saved=await api<Agent>(existing?`/api/v1/agents/${existing.id}`:"/api/v1/agents",{method:existing?"PATCH":"POST",body:JSON.stringify({...draft,version:existing?.version||0})});router.push(`/app/agents/${encodeURIComponent(saved.slug)}`);}catch(e){setError(e instanceof Error?e.message:"保存失败");pending.current=false;setBusy(false)}}
  const toggle=(slug:string)=>setDraft(d=>({...d,skill_slugs:d.skill_slugs.includes(slug)?d.skill_slugs.filter(s=>s!==slug):[...d.skill_slugs,slug]}));
  if (slug && error === "内置 Agent 不支持编辑") return <main className="agent-page"><Header title="编辑 Agent"/><div className="agent-page-body"><p role="alert" className="settings-error">{error}</p><Link href={`/app/agents/${encodeURIComponent(slug)}`}>返回 Agent 详情</Link></div></main>;
  return <main className="agent-page"><Header title={existing?"编辑 Agent":"创建 Agent"}/><div className="agent-page-body"><div className="agent-page-title"><div><p className="eyebrow">Agent studio</p><h1>{existing?`编辑 ${existing.name}`:"创建一个专属 Agent"}</h1><p>自己填写，或先和创建助手聊聊；建议草稿由你确认后才会写入表单。</p></div></div><div className="agent-editor-grid"><form className="agent-form" onSubmit={save}><h2>Agent 设置</h2><label>名称<input required maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="例如：产品需求分析师"/></label><label>简介<input maxLength={500} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="这个 Agent 适合做什么"/></label><label>系统提示词<textarea required maxLength={20000} rows={13} value={draft.instructions} onChange={e=>setDraft({...draft,instructions:e.target.value})} placeholder="说明职责、工作方式、边界和输出格式…"/></label><fieldset><legend>预设 Skill</legend><p>首次使用此 Agent 时，会在会话中安装所选 Skill。</p><div className="agent-skill-list">{skills.map(skill=><label key={skill.slug}><input type="checkbox" checked={draft.skill_slugs.includes(skill.slug)} onChange={()=>toggle(skill.slug)}/><span><strong>{skill.name}</strong><small>{skill.description}</small></span></label>)}</div></fieldset>{error&&<p className="settings-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy}>{busy?"保存中…":existing?"保存修改":"创建 Agent"}</button></form><aside className="agent-builder"><header><Sparkles size={19}/><div><strong>Agent 创建助手</strong><small>聊一聊，整理出可编辑的草稿</small></div></header><div className="agent-builder-messages" aria-live="polite">{messages.map((m,i)=><p key={i} className={m.role}>{m.content}</p>)}{chatBusy&&<p className="assistant">正在整理建议…</p>}</div>{suggestion&&<div className="agent-suggestion"><strong>建议草稿：{suggestion.name}</strong><p>{suggestion.description}</p><button type="button" onClick={()=>{setDraft({...suggestion,skill_slugs:suggestion.skill_slugs.filter(slug=>skills.some(s=>s.slug===slug))});setSuggestion(null)}}>应用到左侧表单</button></div>}{chatError&&<p role="alert" className="settings-error">{chatError}</p>}<form onSubmit={send}><textarea aria-label="给 Agent 创建助手发消息" value={input} onChange={e=>setInput(e.target.value)} rows={3} maxLength={3000} placeholder="例如：我需要一个帮助梳理产品需求的 Agent…"/><button type="submit" disabled={chatBusy||!input.trim()} aria-label="发送给创建助手"><Send size={17}/></button></form></aside></div></div></main>;
}
