"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {ChevronDown,File,FileText,Folder,Menu,Plus,Send,Settings2,TerminalSquare,Wrench,X} from "lucide-react";
import {Brand} from "./brand";
import {ConversationTimeline} from "./conversation-timeline";
import {RunEvent} from "./tool-timeline";
import {API,api,ComputerState,Conversation,Deployment,FileEntry,Message} from "@/lib/api";

const agents=[{slug:"lester",name:"Lester",initial:"L",copy:"冷静、聪明、务实"},{slug:"franklin",name:"Franklin",initial:"F",copy:"直接、高效、重视推进"},{slug:"michael",name:"Michael",initial:"M",copy:"结构化、审慎、质量优先"},{slug:"trevor",name:"Trevor",initial:"T",copy:"大胆、主动、敢于探索"}];
const agentName=(slug:string)=>agents.find(a=>a.slug===slug)?.name||"Lester";

function appendTimelineEvent(previous:RunEvent[],event:RunEvent){if(event.type!=="MODEL_DELTA")return [...previous,event].slice(-1200);const delta=String(event.payload.delta||"");if(!delta)return previous;const last=previous.at(-1);if(last?.type==="MODEL_TEXT"&&last.run_id===event.run_id){return [...previous.slice(0,-1),{...last,payload:{text:String(last.payload.text||"")+delta}}]}return [...previous,{...event,type:"MODEL_TEXT",payload:{text:delta}}].slice(-1200)}

export function Workspace({conversationId}:{conversationId?:string}){const router=useRouter();const[conversations,setConversations]=useState<Conversation[]>([]);const[deployments,setDeployments]=useState<Deployment[]>([]);const[current,setCurrent]=useState<Conversation|null>(null);const[messages,setMessages]=useState<Message[]>([]);const[events,setEvents]=useState<RunEvent[]>([]);const seenEventIds=useRef(new Set<number>());const[dialog,setDialog]=useState(false);const[mobileMenu,setMobileMenu]=useState(false);const[loading,setLoading]=useState(true);
useEffect(()=>{Promise.all([api<{conversations:Conversation[]}>('/api/v1/conversations'),api<{deployments:Deployment[]}>('/api/v1/model-deployments')]).then(([c,d])=>{setConversations(c.conversations);setDeployments(d.deployments)}).finally(()=>setLoading(false))},[]);
useEffect(()=>{if(!conversationId)return;api<{conversation:Conversation;messages:Message[]}>(`/api/v1/conversations/${conversationId}`).then(data=>{setCurrent(data.conversation);setMessages(data.messages)});const stream=new EventSource(`${API}/api/v1/conversations/${conversationId}/events`,{withCredentials:true});stream.onmessage=message=>{const incoming=JSON.parse(message.data) as RunEvent;const event={...incoming,conversation_id:incoming.conversation_id||conversationId};if(seenEventIds.current.has(event.id))return;seenEventIds.current.add(event.id);setEvents(previous=>appendTimelineEvent(previous,event));if(event.type==="RUN_COMPLETED"){api<{conversation:Conversation;messages:Message[]}>(`/api/v1/conversations/${conversationId}`).then(data=>{setCurrent(data.conversation);setMessages(data.messages)})}};return()=>stream.close()},[conversationId]);
async function chooseModel(id:string){if(!conversationId)return;await api(`/api/v1/conversations/${conversationId}`,{method:"PATCH",body:JSON.stringify({model_deployment_id:id})});setCurrent(value=>value?{...value,model_deployment_id:id}:value)}
async function sendMessage(content:string){if(!conversationId)return;const optimisticId=`optimistic-${crypto.randomUUID()}`;const optimisticMessage:Message={id:optimisticId,role:"user",content,created_at:new Date().toISOString()};setMessages(previous=>[...previous,optimisticMessage]);try{await api(`/api/v1/conversations/${conversationId}/messages`,{method:"POST",body:JSON.stringify({content})});const data=await api<{conversation:Conversation;messages:Message[]}>(`/api/v1/conversations/${conversationId}`);setCurrent(data.conversation);setMessages(data.messages)}catch(error){setMessages(previous=>previous.filter(message=>message.id!==optimisticId));throw error}}
return <main className="workspace-shell"><aside className={`conversation-sidebar ${mobileMenu?"mobile-open":""}`}><div className="sidebar-top"><Brand/><button className="icon-button mobile-close" onClick={()=>setMobileMenu(false)} aria-label="关闭"><X/></button><button className="new-button" onClick={()=>setDialog(true)}><Plus/>新对话</button></div><div className="conversation-list">{loading?<p className="muted-block">正在载入…</p>:conversations.map(item=><button key={item.id} className={`conversation-item ${item.id===conversationId?"active":""}`} onClick={()=>router.push(`/app/c/${item.id}`)}><span className="mini-agent">{agentName(item.agent_slug)[0]}</span><span><strong>{item.title}</strong><small>{agentName(item.agent_slug)} · {relativeTime(item.updated_at)}</small></span></button>)}</div><div className="sidebar-footer"><button onClick={()=>router.push('/app/settings/models')}><Settings2/>设置</button></div></aside><section className={`conversation-main ${current?"":"empty-conversation"}`}><header className="conversation-header"><button className="icon-button mobile-menu" onClick={()=>setMobileMenu(true)}><Menu/></button>{current?<><div className="agent-heading"><span className="agent-avatar">{agentName(current.agent_slug)[0]}</span><span><strong>{agentName(current.agent_slug)}</strong><small>Mission · Active</small></span></div><label className="model-selector"><select value={current.model_deployment_id||""} onChange={e=>chooseModel(e.target.value)}>{deployments.length===0&&<option value="">请先配置模型</option>}{deployments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><ChevronDown/></label></>:<><Brand/><button className="new-button mobile-new" onClick={()=>setDialog(true)}><Plus/>新对话</button></>}</header>{current?<ConversationView conversation={current} messages={messages} events={events.filter(event=>event.conversation_id===current.id)} onSend={sendMessage}/>:<EmptyState onNew={()=>setDialog(true)}/>}</section>{current&&<ComputerPanel conversationId={current.id}/>} {dialog&&<NewConversation deployments={deployments} onClose={()=>setDialog(false)}/>}</main>}

function EmptyState({onNew}:{onNew:()=>void}){return <div className="empty-hero"><span className="agent-orbit">L</span><p className="eyebrow">A private directory for every mission</p><h1>把目标交给 Lester</h1><p>选择 Agent 与模型，开始一段拥有独立文件目录、终端和运行历史的对话。</p><button className="primary-button" onClick={onNew}><Plus/>开始新任务</button></div>}
function ConversationView({conversation,messages,events,onSend}:{conversation:Conversation;messages:Message[];events:RunEvent[];onSend:(content:string)=>Promise<void>}){const[text,setText]=useState("");const[busy,setBusy]=useState(false);const thread=useRef<HTMLDivElement>(null);useEffect(()=>{thread.current?.scrollTo({top:thread.current.scrollHeight,behavior:"smooth"})},[messages,events]);async function submit(event:FormEvent){event.preventDefault();if(!text.trim()||busy)return;const content=text.trim();setText("");setBusy(true);try{await onSend(content)}catch{setText(content)}finally{setBusy(false)}}return <><div className="thread" ref={thread}><ConversationTimeline messages={messages} events={events}/></div><form className="composer" onSubmit={submit}><p>Agent 的文件与命令默认进入当前会话目录</p><div className="compose-box"><textarea rows={2} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} placeholder={`给 ${agentName(conversation.agent_slug)} 一个目标…`}/><div className="compose-actions"><button type="button" className="icon-button disabled" disabled title="Uploads arrive in Phase 6"><File/></button><button className="send-button" disabled={busy||!text.trim()}><Send/></button></div></div></form></>}

function NewConversation({deployments,onClose}:{deployments:Deployment[];onClose:()=>void}){const router=useRouter();const[selected,setSelected]=useState('lester');const[model,setModel]=useState(deployments.find(d=>d.is_default)?.id||deployments[0]?.id||"");const[busy,setBusy]=useState(false);async function create(){setBusy(true);try{const item=await api<Conversation>('/api/v1/conversations',{method:'POST',body:JSON.stringify({agent_slug:selected,model_deployment_id:model,title:'新对话'})});router.push(`/app/c/${item.id}`);onClose()}finally{setBusy(false)}}return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal><header><div><p className="eyebrow">New mission</p><h2>选择这段对话的 Agent</h2></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="agent-grid">{agents.map(agent=><button key={agent.slug} className={`agent-option ${selected===agent.slug?'selected':''}`} onClick={()=>setSelected(agent.slug)}><span>{agent.initial}</span><strong>{agent.name}</strong><small>{agent.copy}</small></button>)}</div><label className="field">模型<select value={model} onChange={e=>setModel(e.target.value)}>{deployments.length===0&&<option value="">先去设置模型</option>}{deployments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><footer><button className="secondary-button" onClick={onClose}>取消</button><button className="primary-button" onClick={create} disabled={busy||!model}>{busy?'创建中…':'创建对话'}</button></footer></section></div>}

const computerStatusLabel:Record<ComputerState['status'],string>={not_created:'未创建',creating:'创建中',running:'运行中',suspended:'已暂停',stopped:'已停止',unhealthy:'异常',missing:'待恢复',error:'连接异常'};
function ComputerPanel({conversationId}:{conversationId:string}){const[tab,setTab]=useState<'files'|'terminal'|'skills'>('files');const[state,setState]=useState<ComputerState|null>(null);useEffect(()=>{let active=true;const refresh=()=>api<ComputerState>(`/api/v1/conversations/${conversationId}/computer`).then(value=>{if(active)setState(value)}).catch(()=>{if(active)setState(previous=>previous?{...previous,status:'error'}:null)});refresh();const timer=window.setInterval(refresh,10000);return()=>{active=false;window.clearInterval(timer)}},[conversationId]);const status=state?.status||'not_created';return <aside className="computer-panel"><header><span><i className={`computer-status ${status}`}/>Computer</span><small title={state?.last_error||undefined}>Docker · 用户级 · {computerStatusLabel[status]}</small></header><nav className="computer-tabs"><button className={tab==='files'?'active':''} onClick={()=>setTab('files')}><Folder/>Files</button><button className={tab==='terminal'?'active':''} onClick={()=>setTab('terminal')}><TerminalSquare/>Terminal</button><button className={tab==='skills'?'active':''} onClick={()=>setTab('skills')}><Wrench/>Skills</button></nav>{tab==='files'&&<Files conversationId={conversationId}/>} {tab==='terminal'&&<Terminal conversationId={conversationId}/>} {tab==='skills'&&<div className="skills-empty"><Wrench/><h3>Skills 尚未开放</h3><p>当前只保留产品入口，不提供安装或权限审批能力。</p></div>}</aside>}
function Files({conversationId}:{conversationId:string}){const[result,setResult]=useState<{conversationId:string;files:FileEntry[];error:string}>({conversationId:'',files:[],error:''});useEffect(()=>{let active=true;api<{files:FileEntry[]}>(`/api/v1/conversations/${conversationId}/files`).then(response=>{if(active)setResult({conversationId,files:response.files,error:''})}).catch(error=>{if(active)setResult({conversationId,files:[],error:error.message})});return()=>{active=false}},[conversationId]);const current=result.conversationId===conversationId?result:{conversationId,files:[],error:''};return <div className="files"><div className="pathbar" title={`/workspace/conversations/${conversationId}`}>/ workspace / conversations / {conversationId.slice(0,8)}…</div>{current.error?<p className="muted-block">Computer 暂时不可用：{current.error}</p>:current.files.length===0?<p className="muted-block">当前会话目录还没有文件。</p>:current.files.map(file=><div className="file-row" key={file.path}>{file.is_dir?<Folder/>:<FileText/>}<span><strong>{file.name}</strong><small>{file.is_dir?'Folder':formatBytes(file.size)}</small></span></div>)}</div>}
function Terminal({conversationId}:{conversationId:string}){const mount=useRef<HTMLDivElement>(null);useEffect(()=>{let socket:WebSocket|undefined;let terminal:{dispose:()=>void;write:(v:string)=>void;onData:(fn:(v:string)=>void)=>void}|undefined;(async()=>{const [{Terminal},{FitAddon}]=await Promise.all([import('@xterm/xterm'),import('@xterm/addon-fit')]);if(!mount.current)return;const instance=new Terminal({cursorBlink:true,fontSize:12,theme:{background:'#151a16',foreground:'#dce6dd'}});const fit=new FitAddon();instance.loadAddon(fit);instance.open(mount.current);fit.fit();instance.write('Lester Computer\r\nConnecting…\r\n');const endpoint=new URL(`${API}/api/v1/conversations/${conversationId}/terminal`);endpoint.protocol=endpoint.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(endpoint);socket.onmessage=event=>{const data=JSON.parse(event.data);if(data.Type==='output'||data.type==='output')instance.write(data.Data||data.data)};socket.onopen=()=>instance.onData(data=>socket?.send(JSON.stringify({Type:'input',Data:data})));socket.onerror=()=>instance.write('\r\nTerminal unavailable until the Computer starts.');terminal=instance})();return()=>{socket?.close();terminal?.dispose()}},[conversationId]);return <div className="terminal" ref={mount}/>}
function relativeTime(value:string){const minutes=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000));return minutes<1?'刚刚':minutes<60?`${minutes} 分钟前`:minutes<1440?`${Math.floor(minutes/60)} 小时前`:`${Math.floor(minutes/1440)} 天前`}
function formatBytes(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`}
