"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {Bot,ChevronDown,File,FileText,Folder,Menu,Plus,Send,Settings2,TerminalSquare,Wrench,X} from "lucide-react";
import {Brand} from "./brand";
import {API,api,Conversation,Deployment,FileEntry,Message} from "@/lib/api";

const agents=[{slug:"lester",name:"Lester",initial:"L",copy:"冷静、聪明、务实"},{slug:"franklin",name:"Franklin",initial:"F",copy:"直接、高效、重视推进"},{slug:"michael",name:"Michael",initial:"M",copy:"结构化、审慎、质量优先"},{slug:"trevor",name:"Trevor",initial:"T",copy:"大胆、主动、敢于探索"}];
const agentName=(slug:string)=>agents.find(a=>a.slug===slug)?.name||"Lester";

export function Workspace({conversationId}:{conversationId?:string}){const router=useRouter();const[conversations,setConversations]=useState<Conversation[]>([]);const[deployments,setDeployments]=useState<Deployment[]>([]);const[current,setCurrent]=useState<Conversation|null>(null);const[messages,setMessages]=useState<Message[]>([]);const[live,setLive]=useState("");const[events,setEvents]=useState<Array<{id:number;type:string;payload:Record<string,unknown>}>>([]);const[dialog,setDialog]=useState(false);const[mobileMenu,setMobileMenu]=useState(false);const[loading,setLoading]=useState(true);
useEffect(()=>{Promise.all([api<{conversations:Conversation[]}>('/api/v1/conversations'),api<{deployments:Deployment[]}>('/api/v1/model-deployments')]).then(([c,d])=>{setConversations(c.conversations);setDeployments(d.deployments)}).finally(()=>setLoading(false))},[]);
useEffect(()=>{if(!conversationId)return;api<{conversation:Conversation;messages:Message[]}>(`/api/v1/conversations/${conversationId}`).then(data=>{setCurrent(data.conversation);setMessages(data.messages)});const stream=new EventSource(`${API}/api/v1/conversations/${conversationId}/events`,{withCredentials:true});stream.onmessage=message=>{const event=JSON.parse(message.data);setEvents(previous=>previous.some(item=>item.id===event.id)?previous:[...previous,event].slice(-80));if(event.type==="MODEL_DELTA")setLive(value=>value+String(event.payload.delta||""));if(event.type==="RUN_COMPLETED"){setLive("");api<{conversation:Conversation;messages:Message[]}>(`/api/v1/conversations/${conversationId}`).then(data=>{setCurrent(data.conversation);setMessages(data.messages)})}};return()=>stream.close()},[conversationId]);
async function chooseModel(id:string){if(!conversationId)return;await api(`/api/v1/conversations/${conversationId}`,{method:"PATCH",body:JSON.stringify({model_deployment_id:id})});setCurrent(value=>value?{...value,model_deployment_id:id}:value)}
return <main className="workspace-shell"><aside className={`conversation-sidebar ${mobileMenu?"mobile-open":""}`}><div className="sidebar-top"><Brand/><button className="icon-button mobile-close" onClick={()=>setMobileMenu(false)} aria-label="关闭"><X/></button><button className="new-button" onClick={()=>setDialog(true)}><Plus/>新对话</button></div><div className="conversation-list">{loading?<p className="muted-block">正在载入…</p>:conversations.map(item=><button key={item.id} className={`conversation-item ${item.id===conversationId?"active":""}`} onClick={()=>router.push(`/app/c/${item.id}`)}><span className="mini-agent">{agentName(item.agent_slug)[0]}</span><span><strong>{item.title}</strong><small>{agentName(item.agent_slug)} · {relativeTime(item.updated_at)}</small></span></button>)}</div><div className="sidebar-footer"><button onClick={()=>router.push('/app/settings/models')}><Settings2/>设置</button></div></aside><section className={`conversation-main ${current?"":"empty-conversation"}`}><header className="conversation-header"><button className="icon-button mobile-menu" onClick={()=>setMobileMenu(true)}><Menu/></button>{current?<><div className="agent-heading"><span className="agent-avatar">{agentName(current.agent_slug)[0]}</span><span><strong>{agentName(current.agent_slug)}</strong><small>Mission · Active</small></span></div><label className="model-selector"><select value={current.model_deployment_id||""} onChange={e=>chooseModel(e.target.value)}>{deployments.length===0&&<option value="">请先配置模型</option>}{deployments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><ChevronDown/></label></>:<><Brand/><button className="new-button mobile-new" onClick={()=>setDialog(true)}><Plus/>新对话</button></>}</header>{current?<ConversationView conversation={current} messages={messages} live={live} events={events}/>:<EmptyState onNew={()=>setDialog(true)}/>}</section>{current&&<ComputerPanel conversationId={current.id}/>} {dialog&&<NewConversation deployments={deployments} onClose={()=>setDialog(false)}/>}</main>}

function EmptyState({onNew}:{onNew:()=>void}){return <div className="empty-hero"><span className="agent-orbit">L</span><p className="eyebrow">A private Computer for every mission</p><h1>把目标交给 Lester</h1><p>选择 Agent 与模型，开始一段拥有独立文件、终端和运行历史的对话。</p><button className="primary-button" onClick={onNew}><Plus/>开始新任务</button></div>}
function ConversationView({conversation,messages,live,events}:{conversation:Conversation;messages:Message[];live:string;events:Array<{id:number;type:string;payload:Record<string,unknown>}>}){const[text,setText]=useState("");const[busy,setBusy]=useState(false);const thread=useRef<HTMLDivElement>(null);useEffect(()=>thread.current?.scrollTo({top:thread.current.scrollHeight,behavior:"smooth"}),[messages,live,events]);async function submit(event:FormEvent){event.preventDefault();if(!text.trim()||busy)return;const content=text.trim();setText("");setBusy(true);setLivePlaceholder();try{await api(`/api/v1/conversations/${conversation.id}/messages`,{method:"POST",body:JSON.stringify({content})})}finally{setBusy(false)}}function setLivePlaceholder(){/* SSE supplies the durable render */}return <><div className="thread" ref={thread}>{messages.map(message=><article key={message.id} className={`message-row ${message.role}`}><span className="message-avatar">{message.role==="user"?"W":agentName(conversation.agent_slug)[0]}</span><div className="message-bubble"><p>{message.content}</p><time>{new Date(message.created_at).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}</time></div></article>)}{events.filter(event=>!['MODEL_DELTA','RUN_STARTED','MODEL_STARTED','MODEL_COMPLETED','RUN_COMPLETED'].includes(event.type)).slice(-6).map(event=><div className="activity" key={event.id}><Bot/><span>{eventLabel(event.type)}</span><small>{activityDetail(event.payload)}</small></div>)}{live&&<article className="message-row assistant"><span className="message-avatar">{agentName(conversation.agent_slug)[0]}</span><div className="message-bubble streaming"><p>{live}</p><i/></div></article>}</div><form className="composer" onSubmit={submit}><p>Agent 的文件与命令只存在于当前 Computer</p><div className="compose-box"><textarea rows={2} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} placeholder="给 Lester 一个目标…"/><div className="compose-actions"><button type="button" className="icon-button disabled" disabled title="Uploads arrive in Phase 6"><File/></button><button className="send-button" disabled={busy||!text.trim()}><Send/></button></div></div></form></>}

function NewConversation({deployments,onClose}:{deployments:Deployment[];onClose:()=>void}){const router=useRouter();const[selected,setSelected]=useState('lester');const[model,setModel]=useState(deployments.find(d=>d.is_default)?.id||deployments[0]?.id||"");const[busy,setBusy]=useState(false);async function create(){setBusy(true);try{const item=await api<Conversation>('/api/v1/conversations',{method:'POST',body:JSON.stringify({agent_slug:selected,model_deployment_id:model,title:'新对话'})});router.push(`/app/c/${item.id}`);onClose()}finally{setBusy(false)}}return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal><header><div><p className="eyebrow">New mission</p><h2>选择这段对话的 Agent</h2></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="agent-grid">{agents.map(agent=><button key={agent.slug} className={`agent-option ${selected===agent.slug?'selected':''}`} onClick={()=>setSelected(agent.slug)}><span>{agent.initial}</span><strong>{agent.name}</strong><small>{agent.copy}</small></button>)}</div><label className="field">模型<select value={model} onChange={e=>setModel(e.target.value)}>{deployments.length===0&&<option value="">先去设置模型</option>}{deployments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><footer><button className="secondary-button" onClick={onClose}>取消</button><button className="primary-button" onClick={create} disabled={busy||!model}>{busy?'创建中…':'创建对话'}</button></footer></section></div>}

function ComputerPanel({conversationId}:{conversationId:string}){const[tab,setTab]=useState<'files'|'terminal'|'skills'>('files');return <aside className="computer-panel"><header><span><i/>Computer</span><small>Docker · isolated</small></header><nav className="computer-tabs"><button className={tab==='files'?'active':''} onClick={()=>setTab('files')}><Folder/>Files</button><button className={tab==='terminal'?'active':''} onClick={()=>setTab('terminal')}><TerminalSquare/>Terminal</button><button className={tab==='skills'?'active':''} onClick={()=>setTab('skills')}><Wrench/>Skills</button></nav>{tab==='files'&&<Files conversationId={conversationId}/>} {tab==='terminal'&&<Terminal conversationId={conversationId}/>} {tab==='skills'&&<div className="skills-empty"><Wrench/><h3>Skills arrive in Phase 5</h3><p>这一版只保留产品入口，不提供安装或权限审批能力。</p></div>}</aside>}
function Files({conversationId}:{conversationId:string}){const[files,setFiles]=useState<FileEntry[]>([]);const[error,setError]=useState("");useEffect(()=>{api<{files:FileEntry[]}>(`/api/v1/conversations/${conversationId}/files`).then(r=>setFiles(r.files)).catch(e=>setError(e.message))},[conversationId]);return <div className="files"><div className="pathbar">/ workspace</div>{error?<p className="muted-block">Computer 尚未启动。发送任务后这里会出现文件。</p>:files.map(file=><div className="file-row" key={file.path}>{file.is_dir?<Folder/>:<FileText/>}<span><strong>{file.name}</strong><small>{file.is_dir?'Folder':formatBytes(file.size)}</small></span></div>)}</div>}
function Terminal({conversationId}:{conversationId:string}){const mount=useRef<HTMLDivElement>(null);useEffect(()=>{let socket:WebSocket|undefined;let terminal:{dispose:()=>void;write:(v:string)=>void;onData:(fn:(v:string)=>void)=>void}|undefined;(async()=>{const [{Terminal},{FitAddon}]=await Promise.all([import('@xterm/xterm'),import('@xterm/addon-fit')]);if(!mount.current)return;const instance=new Terminal({cursorBlink:true,fontSize:12,theme:{background:'#151a16',foreground:'#dce6dd'}});const fit=new FitAddon();instance.loadAddon(fit);instance.open(mount.current);fit.fit();instance.write('Lester Computer\r\nConnecting…\r\n');const endpoint=new URL(`${API}/api/v1/conversations/${conversationId}/terminal`);endpoint.protocol=endpoint.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(endpoint);socket.onmessage=event=>{const data=JSON.parse(event.data);if(data.Type==='output'||data.type==='output')instance.write(data.Data||data.data)};socket.onopen=()=>instance.onData(data=>socket?.send(JSON.stringify({Type:'input',Data:data})));socket.onerror=()=>instance.write('\r\nTerminal unavailable until the Computer starts.');terminal=instance})();return()=>{socket?.close();terminal?.dispose()}},[conversationId]);return <div className="terminal" ref={mount}/>}
function relativeTime(value:string){const minutes=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000));return minutes<1?'刚刚':minutes<60?`${minutes} 分钟前`:minutes<1440?`${Math.floor(minutes/60)} 小时前`:`${Math.floor(minutes/1440)} 天前`}
function eventLabel(type:string){return ({COMMAND_STARTED:'正在执行命令',COMMAND_OUTPUT:'命令产生输出',COMMAND_COMPLETED:'命令执行完成',FILE_UPDATED:'文件已更新',RUN_FAILED:'任务执行失败'} as Record<string,string>)[type]||type}
function activityDetail(payload:Record<string,unknown>){return String(payload.command||payload.path||payload.error||'')}
function formatBytes(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`}
