apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lester.fullname" . }}-api
  labels:
    {{- include "lester.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      {{- include "lester.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if not .Values.secrets.existingSecret }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lester.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: {{ include "lester.image" (list .Values.images.api .) }}
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "lester.fullname" . }}-config
            - secretRef:
                name: {{ include "lester.secretName" . }}
          env:
            - name: HTTP_ADDR
              value: :8080
            - name: SANDBOX_SERVICE_URL
              value: http://{{ include "lester.fullname" . }}-sandbox-service:{{ .Values.service.sandboxService.port }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: {path: /healthz, port: http}
          livenessProbe:
            httpGet: {path: /healthz, port: http}
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {drop: ["ALL"]}
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile: {type: RuntimeDefault}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lester.fullname" . }}-api
  labels:
    {{- include "lester.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "lester.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: http
