apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lester.fullname" . }}-web
  labels:
    {{- include "lester.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount.web }}
  selector:
    matchLabels:
      {{- include "lester.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lester.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "lester.image" (list .Values.images.web .) }}
          imagePullPolicy: {{ .Values.images.web.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet: {path: /, port: http}
          livenessProbe:
            httpGet: {path: /, port: http}
          resources:
            {{- toYaml .Values.resources.web | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {drop: ["ALL"]}
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile: {type: RuntimeDefault}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lester.fullname" . }}-web
  labels:
    {{- include "lester.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "lester.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.web.port }}
      targetPort: http
